<?php

namespace App\Support;

use Illuminate\Support\Facades\DB;

/**
 * Medical Record Number generation and validation (ADR-006).
 *
 * The MRN is the ONLY identifier this system can guarantee. Roughly 16 million
 * e-Tazkiras have been issued against a population over 40 million, and there
 * is no national patient identifier at all — so the MRN is generated by us,
 * never derived from a national ID, and never dependent on one existing.
 *
 * It is read aloud across a counter, written on paper, and typed back in by
 * someone who may be working in a second or third language. So it carries a
 * CHECK CHARACTER: a single mistyped or transposed digit is rejected at the
 * point of entry rather than silently opening the wrong patient's chart.
 *
 * The algorithm is Damm, not Luhn. Damm detects all single-digit errors AND all
 * adjacent transpositions; Luhn misses the transposition 09 <-> 90, which is
 * exactly the class of error a hurried clerk makes.
 */
final class MedicalRecordNumber
{
    /**
     * Damm algorithm quasigroup (totally anti-symmetric, order 10).
     * Standard table from H. M. Damm's 2004 dissertation.
     */
    private const MATRIX = [
        [0, 3, 1, 7, 5, 9, 8, 6, 4, 2],
        [7, 0, 9, 2, 1, 5, 4, 8, 6, 3],
        [4, 2, 0, 6, 8, 7, 1, 3, 5, 9],
        [1, 7, 5, 0, 9, 8, 3, 4, 2, 6],
        [6, 1, 2, 3, 0, 4, 5, 9, 7, 8],
        [3, 6, 7, 4, 2, 0, 9, 5, 8, 1],
        [5, 8, 6, 9, 7, 2, 0, 1, 3, 4],
        [8, 9, 4, 5, 3, 6, 2, 0, 1, 7],
        [9, 4, 3, 8, 6, 1, 7, 2, 0, 5],
        [2, 5, 8, 1, 4, 3, 6, 7, 9, 0],
    ];

    /**
     * Allocate the next MRN for a facility.
     *
     * Draws from the row-locked number_series table rather than a Postgres
     * SEQUENCE, so the series is gapless even when a transaction rolls back.
     */
    public static function next(string $facilityId): string
    {
        $base = DB::selectOne(
            'SELECT next_number(?, ?) AS mrn',
            [$facilityId, 'MRN']
        )->mrn;

        return self::withCheckDigit($base);
    }

    /**
     * Append a check digit: MRN-000123 -> MRN-000123-4
     */
    public static function withCheckDigit(string $value): string
    {
        return $value.'-'.self::checkDigit(self::digits($value));
    }

    /**
     * Is this a structurally valid MRN?
     *
     * Format only — it says nothing about whether the patient exists. Callers
     * should use this to reject typos before hitting the database, so that a
     * mistyped MRN produces "that is not a valid number" rather than a
     * confusing empty result.
     */
    public static function isValid(?string $value): bool
    {
        if ($value === null || $value === '') {
            return false;
        }

        // Users type Persian digits; normalize before validating (ADR-007).
        $digits = self::digits(TextNormalizer::normalizeInput($value) ?? '');

        // Need at least one payload digit plus the check digit.
        if (strlen($digits) < 2) {
            return false;
        }

        return self::checkDigit($digits) === 0;
    }

    /**
     * Compute the Damm check digit for a digit string.
     *
     * Returns 0 when the string already includes a valid check digit, which is
     * what makes validation a single pass over the whole value.
     */
    public static function checkDigit(string $digits): int
    {
        $interim = 0;

        foreach (str_split($digits) as $digit) {
            $interim = self::MATRIX[$interim][(int) $digit];
        }

        return $interim;
    }

    /** Strip everything that is not an ASCII digit. */
    private static function digits(string $value): string
    {
        return preg_replace('/\D+/', '', $value) ?? '';
    }

    /**
     * Normalize user input into the canonical stored form.
     *
     * A clerk may type "mrn 000123 4", "MRN-000123-4", or the same with Persian
     * digits. All must resolve to one lookup key.
     */
    public static function normalize(?string $value): ?string
    {
        if ($value === null) {
            return null;
        }

        $digits = self::digits(TextNormalizer::normalizeInput($value) ?? '');

        if ($digits === '') {
            return null;
        }

        $check = substr($digits, -1);
        $body = substr($digits, 0, -1);

        return sprintf('MRN-%s-%s', str_pad($body, 6, '0', STR_PAD_LEFT), $check);
    }
}
